# Generated by Django 4.2 on 2025-06-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAMble', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='profile_picture',
            field=models.CharField(default='tutors/default.jpg', max_length=255),
        ),
    ]
