# Generated by Django 4.2 on 2025-06-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAMble', '0003_tutor_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='tutor_profiles/'),
        ),
    ]
