# Generated by Django 4.2 on 2025-05-27 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RAMble', '0002_tutor_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='schedule',
        ),
        migrations.CreateModel(
            name='TutorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.TimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='RAMble.tutor')),
            ],
            options={
                'unique_together': {('tutor', 'date', 'time_slot')},
            },
        ),
    ]
