# Generated by Django 4.2 on 2025-05-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAMble', '0003_remove_tutor_schedule_tutoravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tutor',
            name='subjects',
            field=models.ManyToManyField(related_name='tutors', to='RAMble.subject'),
        ),
    ]
